# 1

<b>If the square matrix A is not invertible, why is it "likely" that the inho-
mogeneous equation is inconsistent? "Likely", in this case, means that the
system should be inconsistent for a y chosen at random</b>

If it is not invertible, it means that when we take it to its reduced form, at least one of the rows will not have a leading entry; that is, will be all zeros. Now, if we imagine that we put a vector $\vec{y}$ on the right side with $A\vec{x} = \vec{y}$, then zooming into that particular row which became zero will give us this equation:

\begin{equation*}
0x_1 + 0x_2 \cdots + 0x_m = y_i
\end{equation*}

Now, in order to have solutions on the system we need a $y_i$ that is non zero. But all its possible values are $\mathbb{R}$, thus, is certainly more likely that we pick a non zero entry. Therefore, if we pick a $y \in \mathbb{R}$ randomly, is more likely that the system $A\vec{x} = \vec{y}$ will not have solutions.

## 2
<b>If A and B are square matrices of the same size, then $det(AB) = det(A)det(B)$ 

(a) Prove this last statement (Hint the elementary matrices).</b>

We will have two sub-proofs, for the respective cases of $A$ being invertible or not (same could be done for $B$, but let us just choose $A$).

#### case 1) $A$ is not invertible

There is another result that claims that if $A$ is singular and square, and if multiplied by another arbitrary matrix $B$; then the result $AB$ will be another singular matrix. In other words, this results tells us that the singularity is like a disease that gets transmited through multiplication. 

Is not hard to prove if we think in terms of linears transformations. The following chain of logical statements does the informal proof:

<ul>
<li>Assume $B$ is a biyection of $\mathbb{R}^n \implies \mathbb{R}^n$.</li>
<li>Assume $A$ is singular.</li>
<li>$A$ sends a non-trivial subspace $N(A)$, the kernel, into zero.</li>
<li>$AB$ is a composition of two linear transformations $B$ and $A$.</li>
<li>Since $A$ is not a biyection, once we compose $B$ with $A$ through $AB$, we are doomed to loose biyection of $B$ ($AB$ will have non trivial kernel too). </li>
<li>Therefore, $AB$ is non singular as well.</li>
</ul>

Now, let us remember another result (the negated form of this is proved in exercise 4).

$A$ is singular $\iff$ $det(A)=0$

Using these two weapons, we can know prove this subcase of the theorem, because we know that both $A$ and $AB$ are singular:

$\therefore\; det(AB) = 0 = 0\, det(B) = det(A)\, det(B)$

#### case 2) $A$ is invertible

Let us know move into the more interesting case of $A$ being invertible. 

If $A$ is invertible then $\exists\,A^{-1}$ and $A^{-1}\,A = I$. We also know that the inverse is nothing but the application of elementary matrices (those that took $A$ into $I$ in Guass-Jordan algorithm):

\begin{equation*}
\prod_{i=1}^k E_i = A^{-1}
\end{equation*}

But by properties of elementary matrices and the product, we know that $A$ is also built out of elementary matrices (precisely, the inverse of those $E_i$):

\begin{equation*}
\prod_{i=1}^k E_{k-i+1}^{-1} = A
\end{equation*}

Let us use above theorem and rewrite a little $det(AB)$

\begin{equation*}
det(AB) = det\left(\prod_{i=1}^k E_{k-i+1}^{-1} B\right)
\end{equation*}

On the other hand, in notes and in class we saw the that the elementary matrices do not alter much the determinant, actually, they just vary original determinant by a constant (last statement refers to the operation of adding a multiple of another row):

<ol>
<li>$det(cA) = cdet(A)$</li>
<li>$det(swap(A,i,j)) = -det(A)$</li>
<li>$det(\{A_i := A_i + kA_j\}) = det(A)$</li>
</ol>

Putting together these results, we can prove a kind of useful theorem that says something like this:

\begin{equation*}
det\left(\prod_{i=1}^k E_i A\right) = \left(\prod_{i=1}^k \alpha_i\right)\,det(A) = \alpha \, det(A)
\end{equation*}

in other words, we are saying that applying a series of elementary matrices does not alter the original determinant beyond a constant. This could be proved by example, using induction over the $n$ and doing analysis by cases depending on the type of elementary operation; but we will omit this proof for brevity.

Applying the latest theorem to our development of $A$ as product of elementary matrices, leads us to:


\begin{equation*}
det(AB) = det\left(\prod_{i=1}^k E_{n-i+1}^{-1} B\right) = \alpha\, det(B)
\end{equation*}

We could take out the $det(B)$, and what is left is to prove that $\alpha = det(A)$. For this we express again $A$ as the product of elementary matrices (same ones used above), and the fact that $A\,A^{-1} = I$

\begin{equation*}
1 = det(I) = det(A\,A^{-1}) = det\left(\prod_{i=1}^k E_{n-i+1}^{-1} A^{-1}\right) = \alpha\,det(A^{-1})
\end{equation*}

Above development immediately leads to expected result (using an additional theorem that relates the determinants of $A$ and $A^{-1}$):

\begin{equation*}
1 = \alpha\,det(A^{-1}) \;\implies\; \alpha = \frac{1}{det(A^{-1})} = \frac{\frac{1}{1}}{\frac{1}{det(A)}} = det(A)
\end{equation*}

We can conclude now this case:

\begin{equation*}
det(AB) = \alpha\,det(B) \,\land\, det(A) = \alpha 
\;\implies\; det(AB) = det(A)\,det(B)\; \therefore
\end{equation*}

The two sub-proofs, for $A$ being singular and invertible, compose the proof of the whole theorem and we are done.


# 3
<b>If A is an upper triangular matrix with one or more 0's on the main
diagonal, then det(A) = 0.</b>

In class we saw that if $A$ is upper triangular, then

\begin{equation*}
det(A) = \prod_{i=1}^k A_{ii}
\end{equation*}

clearly, if any of those $A_{ii}$ becomes zero the whole product becomes zero; leading to $det(A) = 0$.

# 4
<b>Show that A is invertible $\iff$ $det(A) \neq 0$.</b>

#### first part, $A$ invertible $\implies$ $det(A) \neq 0$

If $A$ is invertible then we can apply elementary operations against it, and take it to upper triangular form $R$ (echelon form). But per previous results mentioned in this homework, we know that doing that will vary the original determinant by a constant only.

\begin{equation*}
det(R) = det\left(\prod_{i=1}^k E_i\,A\right) = \gamma\,det(A)
\end{equation*}

Now, since $A$ is invertible we know that $R$ will have all its diagonal with leading entries (ones). We also know how to compute the determinant of $R$

\begin{equation*}
det(R) = \prod_{i=1}^n R_{ii} = 1
\end{equation*}

Combining these two results leads to:

\begin{equation*}
\gamma\,det(A) = 1 \;\implies\; det(A) = \frac{1}{\gamma}
\end{equation*}

$det(A)$ must be non zero, because $\frac{1}{\gamma}$ is well defined and non zero. This is because $\gamma$ comes from the application of elementary matrices (the constants they add to $det(A)$ are never zero). 

#### second part, $det(A) \neq 0$ $\implies$ $A$ invertible

Let us apply again Gauss-Jordan against $A$ and obtain its echelon form $R$. We know that the determinant of this matrix relates to $det(A)$ by a constant.

\begin{equation*}
det(R) = \beta \, det(A)
\end{equation*}

If $det(A) \neq 0$ then $det(R) \neq 0$ (by above equation, as $\beta$ is non zero for coming out of elementary operations). 

Now, if $R$ has a non zero determinant, it means that all its diagonal has non zero elements. But this will mean that all its columns are linearly independent, which in turn implies the same for $A$. 

And finally, by another theorem seen in the notes, we know that if $A$ has all its columns linearly independent then $A$ is invertible. 


# 5
<b>Implement the calculus of the determinant using the echelon idea.</b>

We already have implemented the Gauss-Jordan algorithm, by left multiplying original matrix $A$ by elementary matrices $E_i$. By the theorems referred in previous exercises, we know that each one of those $E_i$ will alter the $det(A)$ by a constant only. Let us supposed that $A$ is invertible, hence the determinant of its reduced echelon form will be $1$; leading to:

\begin{equation*}
1 = det(R) = det\left(\prod_{i=1}^k E_i \,A\right) = \gamma\,det(A)
\end{equation*}

In other words:

\begin{equation*}
det(A) = \frac{1}{\gamma}
\end{equation*}

That is, we just multiply the constants associated with the $E_i$; and if the result is non zero, we return its inverse multiplicative as $det(A)$. If the product is zero, we know that $det(A) = 0$.

Modified code below.


In [35]:
import numpy as np

BRO_MULT = 1
BRO_ADDMULT = 2
BRO_SWAP = 3

class BasicRowOper:
    def __init__(self, bro_type, src, k, dst):
        self.bro_type = bro_type
        self.src = src
        self.k = k
        self.dst = dst
        
    def __str__(self):
        return "(%s, %d, %f, %d, det_cte=%f)" % (self.bro_type, \
                                     self.src, self.k, self.dst, \
                                     self.det_cte)
        
    # builds the matrix that represents the basic operation
    def _basic_matrix(self, n):
        bmat = np.identity(n)
        if self.bro_type == BRO_MULT:      
            assert self.dst == self.src
            bmat[self.dst] = self.k * bmat[self.src]
        elif self.bro_type == BRO_ADDMULT:
            bmat[self.dst] += self.k * bmat[self.src]
        elif self.bro_type == BRO_SWAP:
            bmat[[self.src, self.dst]] = bmat[[self.dst, self.src]]
        else:
            raise ValueError("Invalid basic row operation type")
        return bmat
    
    # also returns the cte associated with elementary matrix 
    def apply(self, mat):
        n, _ = mat.shape
        mat[:,:] = np.dot(self._basic_matrix(n), mat)         
        print("%s: after\n%s\n" % (self, mat))
        return self.det_cte
    
class BroMult(BasicRowOper):
    def __init__(self, k, dst):
        BasicRowOper.__init__(self, BRO_MULT, dst, k, dst)
        self.det_cte = k

class BroAddMult(BasicRowOper):
    def __init__(self, src, k, dst):
        BasicRowOper.__init__(self, BRO_ADDMULT, src, k, dst)
        self.det_cte = 1
        
class BroSwap(BasicRowOper):
    def __init__(self, src, dst):
        BasicRowOper.__init__(self, BRO_SWAP, src, 1, dst)
        self.det_cte = -1

def make_one(mat, i, j):
    det_cte = 1
    if mat[i][j] == 0:
        nzi = np.nonzero(mat[:,j][i:])[0]
        assert nzi.size > 0        
        det_cte *= BroSwap(i, nzi[0]).apply(mat)
    if mat[i][j] != 1:        
        det_cte *= BroMult(1.0/mat[i][j], i).apply(mat)
    return det_cte
    
def make_zero(mat, i, j, pivot):
    det_cte = 1
    if mat[i][j] != 0:
        assert mat[pivot][j] == 1, \
            "invalid pivot (%d,%d,%d) %f" % (i, j, pivot, mat[pivot][j])
        det_cte *= BroAddMult(pivot, -mat[i][j], i).apply(mat)
    return det_cte
    
def pivot(mat, j, below=True):
    n, _ = mat.shape
    if below:
        row_idx = xrange(j+1, n)
    else:
        row_idx = xrange(j-1, -1, -1)
    det_cte = make_one(mat, j, j)
    for i in row_idx:
        det_cte *= make_zero(mat, i, j, j)
    return det_cte
     
# returns both the reduced form and det(A)    
def gauss_jordan_det(A):
    n, m = A.shape
    assert n == m
    mat = np.empty_like (A)
    mat[:] = A
    det_cte = 1
    for j in xrange(n):
        det_cte *= pivot(mat, j)
    for j in xrange(n-1, -1, -1):
        det_cte *= pivot(mat, j, False)  
    det_A = 1/det_cte if det_cte != 0 else 0
    return mat, det_A
        

Let us test our modified routines with same matrix we used on homework one; and compare that with numpy built-in determinant function.

In [36]:
A = np.array([[1,1,1], [2,3,5], [4,0,5]])
R, det_A = gauss_jordan_det(A)
print("our computed det(A) = %f " % det_A)
print("numpy det(A) = %f " % np.linalg.det(A))

(2, 0, -2.000000, 1, det_cte=1.000000): after
[[1 1 1]
 [0 1 3]
 [4 0 5]]

(2, 0, -4.000000, 2, det_cte=1.000000): after
[[ 1  1  1]
 [ 0  1  3]
 [ 0 -4  1]]

(2, 1, 4.000000, 2, det_cte=1.000000): after
[[ 1  1  1]
 [ 0  1  3]
 [ 0  0 13]]

(1, 2, 0.076923, 2, det_cte=0.076923): after
[[1 1 1]
 [0 1 3]
 [0 0 1]]

(2, 2, -3.000000, 1, det_cte=1.000000): after
[[1 1 1]
 [0 1 0]
 [0 0 1]]

(2, 2, -1.000000, 0, det_cte=1.000000): after
[[1 1 0]
 [0 1 0]
 [0 0 1]]

(2, 1, -1.000000, 0, det_cte=1.000000): after
[[1 0 0]
 [0 1 0]
 [0 0 1]]

our computed det(A) = 13.000000 
numpy det(A) = 13.000000 


# 6
<b>Implement the algorithm to obtain inverses from squared matrices using
jupyter notebook.</b>

In a similar spirit to previous exercise, we will leverage Gauss-Jordan algorithm that we have. We will simply apply same elementary operations against the extended matrix $[A \;|\; I]$. At the end, we will have $[I \;|\; A^{-1}]$.

Below the modified Gauss-Jordan routine (we could integrate the computation of determinant, to know whether inverse actually exist; but just handle non-singular case now due lack of time):

In [37]:
# need to patch the apply function to consider extended matrix
def ext_apply(self, mat):
    n, m = mat.shape
    mat[:,:n] = np.dot(self._basic_matrix(n), mat[:, :n])
    mat[:,n:m] = np.dot(self._basic_matrix(n), mat[:, n:m])
    print("%s: after\n%s\n" % (self, mat))
    return self.det_cte
    
BasicRowOper.apply = ext_apply

# returns the inverse of A
def gauss_jordan_inv(A):
    n, m = A.shape
    assert n == m
    mat = np.zeros(shape=(n, 2*n))
    mat[:, :n] = A
    mat[:, n:2*n] = np.identity(n)
    for j in xrange(n):
        pivot(mat, j)
    for j in xrange(n-1, -1, -1):
        pivot(mat, j, False) 
    inv_A = mat[:, n:2*n]
    return inv_A

Simiarly to previous exercise, we test with same matrix and compare the result with numpy's integrated inverse function.

In [38]:
A = np.array([[1,1,1], [2,3,5], [4,0,5]])
inv_A = gauss_jordan_inv(A)
print("our computed inv(A) =\n" + str(inv_A))
print("\nnumpy inv(A) =\n"  + str(np.linalg.inv(A)))
print("\ndifference between both = \n"  + str(inv_A - np.linalg.inv(A)))

(2, 0, -2.000000, 1, det_cte=1.000000): after
[[ 1.  1.  1.  1.  0.  0.]
 [ 0.  1.  3. -2.  1.  0.]
 [ 4.  0.  5.  0.  0.  1.]]

(2, 0, -4.000000, 2, det_cte=1.000000): after
[[ 1.  1.  1.  1.  0.  0.]
 [ 0.  1.  3. -2.  1.  0.]
 [ 0. -4.  1. -4.  0.  1.]]

(2, 1, 4.000000, 2, det_cte=1.000000): after
[[  1.   1.   1.   1.   0.   0.]
 [  0.   1.   3.  -2.   1.   0.]
 [  0.   0.  13. -12.   4.   1.]]

(1, 2, 0.076923, 2, det_cte=0.076923): after
[[ 1.          1.          1.          1.          0.          0.        ]
 [ 0.          1.          3.         -2.          1.          0.        ]
 [ 0.          0.          1.         -0.92307692  0.30769231  0.07692308]]

(2, 2, -3.000000, 1, det_cte=1.000000): after
[[ 1.          1.          1.          1.          0.          0.        ]
 [ 0.          1.          0.          0.76923077  0.07692308 -0.23076923]
 [ 0.          0.          1.         -0.92307692  0.30769231  0.07692308]]

(2, 2, -1.000000, 0, det_cte=1.000000): after
[[ 1.